#!/usr/bin/env bash

# Simple script to create an S3 bucket
# Usage: ./create-bucket <bucket-name>

if [ -z "$1" ]; then
  echo "Usage: ./create-bucket <bucket-name>"
  exit 1
fi

BUCKET_NAME="$1"

echo "Creating bucket: $BUCKET_NAME"
aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1
