#!/usr/bin/env bash

echo "  == delete-bucket "

#check for the bucket name
if [ -z "$1" ]; then
  echo "There need to be a bucket name eg. ./delete-bucket kshitijsinghania-bucket"
  exit 1
fi

aws s3api delete-bucket \
--bucket "$1"