#!/usr/bin/env bash

echo " == list-objects "

#check for the bucket name
if [ -z "$1" ]; then
  echo "There need to be a bucket name eg. ./list-objects kshitijsinghania-bucket"
  exit 1
fi

aws s3api list-objects \
--bucket "$1"