#!/usr/bin/env bash

# Simple script to upload a file to S3
# Usage: ./put-object <bucket-name> <key> <local-file>

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
  echo "Usage: ./put-object <bucket-name> <key> <local-file>"
  exit 1
fi

BUCKET_NAME="$1"
KEY="$2"
FILE="$3"

echo "Uploading $FILE to s3://$BUCKET_NAME/$KEY"
aws s3 cp "$FILE" "s3://$BUCKET_NAME/$KEY"
